version: '3'

services:

    angular:
        build: ./src
        ports:
            - 4200:4200
        command: >
            bash -c "npm install && ng serve --host 0.0.0.0 --port 4200"

    php:
        build: ./php
        ports:
        - 80:80
        volumes:
        - ./php:/var/www/html
        depends_on:
        - mysql

    mysql:
        build: ./mysql
        ports:
            - 3306:3306
        environment:
            MYSQL_DATABASE: 'menu'
        volumes:
            - db-volume:/var/lib/mysql

volumes:
    db-volume: